# Generated by Django 3.0.5 on 2020-04-06 03:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitsoAcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitsomail', models.EmailField(max_length=100)),
                ('bitsokey', models.CharField(max_length=30)),
                ('bitsosecret', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperationAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='No description', max_length=250)),
                ('Balance', models.FloatField(default=0)),
                ('Actions', models.FloatField(default=0)),
                ('ValorExpected', models.FloatField(default=0)),
                ('DigitalCoin', models.CharField(choices=[('btc', 'btc'), ('eth', 'eth')], default='btc', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BitsoDataConfig',
            fields=[
                ('BitsoAcount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bitsoScaner.BitsoAcount')),
                ('ConfigName', models.CharField(max_length=100)),
                ('bitsoScanerRefresh', models.DecimalField(decimal_places=0, max_digits=2)),
                ('MailReceivers', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SenderMailAccount',
            fields=[
                ('MailAccount', models.EmailField(max_length=100)),
                ('MailKey', models.CharField(max_length=100)),
                ('BitsoDataConfig', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bitsoScaner.BitsoAcount')),
            ],
        ),
        migrations.CreateModel(
            name='BitsoBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BalanceUpdate', models.DateField(default=django.utils.timezone.now)),
                ('BalanceCoin', models.CharField(choices=[('btc', 'btc'), ('eth', 'eth'), ('mxn', 'mxn')], default='btc', max_length=10)),
                ('Balance', models.FloatField(default=0)),
                ('BitsoAcount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitsoScaner.BitsoAcount')),
            ],
        ),
        migrations.CreateModel(
            name='OperationSellTo',
            fields=[
                ('operationaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bitsoScaner.OperationAction')),
                ('BuyDate', models.DateField(default=django.utils.timezone.now)),
                ('BuyHour', models.TimeField()),
                ('ValorCompra', models.FloatField(default=0)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitsoScaner.BitsoAcount')),
            ],
            bases=('bitsoScaner.operationaction',),
        ),
        migrations.CreateModel(
            name='OperationBuy',
            fields=[
                ('operationaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bitsoScaner.OperationAction')),
                ('buystatus', models.CharField(max_length=100)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitsoScaner.BitsoAcount')),
            ],
            bases=('bitsoScaner.operationaction',),
        ),
    ]
