# Generated by Django 3.0.5 on 2020-04-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitsoScaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaction',
            name='SendMail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bitsobalance',
            name='BalanceCoin',
            field=models.CharField(choices=[('btc', 'btc'), ('eth', 'eth'), ('ltc', 'ltc'), ('mxn', 'mxn')], default='btc', max_length=10),
        ),
        migrations.AlterField(
            model_name='operationaction',
            name='DigitalCoin',
            field=models.CharField(choices=[('btc', 'btc'), ('eth', 'eth'), ('ltc', 'ltc')], default='btc', max_length=10),
        ),
    ]
