# Generated by Django 3.0.5 on 2020-04-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitsoScaner', '0002_auto_20200421_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitsodataconfig',
            name='MailReceivers',
        ),
        migrations.AddField(
            model_name='sendermailaccount',
            name='MailReceivers',
            field=models.EmailField(default='cadgo@hotmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
