# Generated by Django 3.0.5 on 2020-04-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitsoScaner', '0003_auto_20200422_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendermailaccount',
            old_name='BitsoDataConfig',
            new_name='BitsoAcount',
        ),
    ]
