# Generated by Django 3.0.5 on 2020-04-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitsoScaner', '0004_auto_20200422_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationaction',
            name='Actions',
        ),
        migrations.RemoveField(
            model_name='operationbuy',
            name='buystatus',
        ),
    ]
